// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entityFrameworkTest_ConsoleApp.DAL;

namespace entityFrameworkTest_ConsoleApp.Migrations
{
    [DbContext(typeof(PeopleContext))]
    [Migration("20180911153525_require_address")]
    partial class require_address
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("entityFrameworkTest_ConsoleApp.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Credits");

                    b.Property<string>("Name");

                    b.Property<int?>("ProfessorID");

                    b.HasKey("ID");

                    b.HasIndex("ProfessorID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("entityFrameworkTest_ConsoleApp.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("ID");

                    b.ToTable("People");
                });

            modelBuilder.Entity("entityFrameworkTest_ConsoleApp.Models.PersonAddress", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<string>("Line1");

                    b.Property<string>("Line2");

                    b.Property<int>("PersonID");

                    b.Property<string>("State");

                    b.Property<int>("ZipCode");

                    b.HasKey("ID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("PersonAddress");
                });

            modelBuilder.Entity("entityFrameworkTest_ConsoleApp.Models.Registration", b =>
                {
                    b.Property<int>("PersonID");

                    b.Property<int>("CourseID");

                    b.Property<int?>("Grade");

                    b.Property<int>("ID");

                    b.HasKey("PersonID", "CourseID");

                    b.HasIndex("CourseID");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("entityFrameworkTest_ConsoleApp.Models.Course", b =>
                {
                    b.HasOne("entityFrameworkTest_ConsoleApp.Models.Person", "Professor")
                        .WithMany("CoursesTeaching")
                        .HasForeignKey("ProfessorID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("entityFrameworkTest_ConsoleApp.Models.PersonAddress", b =>
                {
                    b.HasOne("entityFrameworkTest_ConsoleApp.Models.Person", "Person")
                        .WithOne("PersonAddress")
                        .HasForeignKey("entityFrameworkTest_ConsoleApp.Models.PersonAddress", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("entityFrameworkTest_ConsoleApp.Models.Registration", b =>
                {
                    b.HasOne("entityFrameworkTest_ConsoleApp.Models.Course", "Course")
                        .WithMany("Registrations")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("entityFrameworkTest_ConsoleApp.Models.Person", "Person")
                        .WithMany("Registrations")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
